name: blockshield
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_core_web: ^2.17.5
  firebase_auth_web: ^5.12.6
  cloud_firestore_web: ^4.1.2
  web3dart: ^2.6.1
  http: ^1.2.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3
  flutter_dotenv: ^5.1.0
  crypto: ^3.0.2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.15
  logging: ^1.0.2  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ThreatDataContract.json
    - assets/ReputationContract.json
